// MOVEMENTS
export const FLAT_BENCH =  "FLAT_BENCH";
export const ADD_FLAT_BENCH_SET = "ADD_FLAT_BENCH_SET";
export const DECLINE_BENCH = "DECLINE_BENCH";
export const INCLINE_BENCH = "INCLINE_BENCH";