/*
    EACH MOVEMENT SHOULD HAVE ITS OWN ADD AND DELETE SETS REDUCER
*/

// MOVEMENTS
export const FLAT_BENCH =  "FLAT_BENCH";
export const DECLINE_BENCH = "DECLINE_BENCH";
export const INCLINE_BENCH = "INCLINE_BENCH";

// Add Sets
export const ADD_FLAT_BENCH_SET = "ADD_FLAT_BENCH_SET";
export const ADD_INCLINE_BENCH_SET = "ADD_INCLINE_BENCH_SET";
export const ADD_DECLINE_BENCH_SET = "ADD_DECLINE_BENCH_SET";

// Delete Sets
export const DELETE_FLAT_BENCH_SET = "DELETE_FLAT_BENCH_SET";
export const DELETE_INCLINE_BENCH_SET = "DELETE_INCLINE_BENCH_SET";
export const DELETE_DECLINE_BENCH_SET = "DELETE_DECLINE_BENCH_SET";